apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-quota-demoj
spec:
  selector:
    matchLabels:
      purpose: quota-demoj
  replicas: 3
  template:
    metadata:
      labels:
        purpose: quota-demoj
    spec:
      containers:
      - name: pod-quota-demoj
        image: nginx