apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb1-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: master.example.local
    path: /nfsdata/dat2
