version: '3'
services:
    mssql:
        image: raentena/sql2019:CU5
        restart: always
        container_name: mssql
        environment:
            MSSQL_PID: Evaluation
        volumes:
            - sql:/var/opt/mssql 
        ports:
            - "1433:1433"
    
    webapp:
        image: raentena/webapp:final
        container_name: webapp
        environment:
            DBSVR: mssql
        restart: always
        depends_on:
            - mssql
        ports:
            - "80:3000"
volumes:
        sql:
            driver_opts: 
                type: none
                device: /sql
                o: bind