apiVersion: v1
kind: Pod
metadata:
  name: mongodb1 
spec:
  containers:
  - image: mongo
    name: mongodb1
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb1-pvc

